# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fetcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(454, 207)
        self.radioButton_fetch = QtWidgets.QRadioButton(Form)
        self.radioButton_fetch.setGeometry(QtCore.QRect(10, 50, 112, 23))
        self.radioButton_fetch.setObjectName("radioButton_fetch")
        self.radioButton_url = QtWidgets.QRadioButton(Form)
        self.radioButton_url.setGeometry(QtCore.QRect(150, 50, 112, 23))
        self.radioButton_url.setObjectName("radioButton_url")
        self.radioButton_sheet = QtWidgets.QRadioButton(Form)
        self.radioButton_sheet.setGeometry(QtCore.QRect(290, 50, 112, 23))
        self.radioButton_sheet.setObjectName("radioButton_sheet")
        self.lineEdit_url = QtWidgets.QLineEdit(Form)
        self.lineEdit_url.setGeometry(QtCore.QRect(50, 80, 391, 25))
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 84, 41, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 114, 161, 17))
        self.label_2.setObjectName("label_2")
        self.checkBox_audio = QtWidgets.QCheckBox(Form)
        self.checkBox_audio.setGeometry(QtCore.QRect(10, 140, 101, 23))
        self.checkBox_audio.setObjectName("checkBox_audio")
        self.comboBox_sheetname = QtWidgets.QComboBox(Form)
        self.comboBox_sheetname.setGeometry(QtCore.QRect(180, 110, 261, 25))
        self.comboBox_sheetname.setObjectName("comboBox_sheetname")
        self.pushButton_fetch = QtWidgets.QPushButton(Form)
        self.pushButton_fetch.setGeometry(QtCore.QRect(350, 170, 89, 25))
        self.pushButton_fetch.setObjectName("pushButton_fetch")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_status = QtWidgets.QLabel(Form)
        self.label_status.setGeometry(QtCore.QRect(10, 180, 321, 17))
        self.label_status.setObjectName("label_status")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.radioButton_fetch.setText(_translate("Form", "Fetch All"))
        self.radioButton_url.setText(_translate("Form", "Single URL"))
        self.radioButton_sheet.setText(_translate("Form", "Single Sheet"))
        self.label.setText(_translate("Form", "URL"))
        self.label_2.setText(_translate("Form", "Spreadsheet Filename"))
        self.checkBox_audio.setText(_translate("Form", "Audio Only"))
        self.pushButton_fetch.setText(_translate("Form", "Fetch!"))
        self.label_3.setText(_translate("Form", "Fetcher"))
        self.label_status.setText(_translate("Form", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
